### ISSUE TITLE
v0.1.2 Touchscreen touch rotation not right 

### ISSUE THREAD

**Issue by liyiecho** [setville/redmi2pi-klipperOS#1]
when I touch it on left down , it trigger the left up.
touch it on letf up , it trigger the right up.
touch it on right up , it trigger the right down.
touch it on right down , it trigger the left down.

**Comment by setville** [comment]
will try and fix in 8 hours seems i missed the udev rule for screen calibration.

**Comment by liyiecho** [comment]
I found the problem, the display in your udev rule is `generic ft5x06 (3b)`, but my display is `generic ft5x06 (51)`, so the screen calibration is not right. After I change it, it works now.
<img width="968" alt="QQ20240612-144506@2x" src="https://github.com/setville/redmi2pi-klipperOS/assets/5213722/9022c27c-0e95-4c47-a77a-effd1062554a">

**Comment by setville** [comment]
i could test putting in a wildcard in touchscreen udev rule to cover all generic ft5x06's. thanks @liyiecho.

**Comment by setville** [comment]
testing udev rule now and will update release later.

edit 20240613001900: fixed ft5x06 udev rule.
